name: Containerize
env:
  PACKAGE_NAME: 'quickfs'

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set default tag
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: echo "TAG_NAME=latest" >> $GITHUB_ENV

      - name: Build go code
        run: |
          mkdir -p build
          docker run --rm -v ${{ github.workspace }}:/app -w /app golang:1.25-alpine sh -c "GOOS=linux GOARCH=amd64 go build -o build/api.amd64 -ldflags '-s -w' . && GOOS=linux GOARCH=arm64 go build -o build/api.arm64 -ldflags '-s -w' ."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .build/prod.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:${{ env.TAG_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:latest
